import React,{useEffect,useState} from "react";
import {api} from "../api";
import {useToast} from "../Toast";
import Icon from "../icons";
const STAGE_LABELS={INTAKE:"Denial intake",EXTRACTION:"Field extraction",CLASSIFICATION:"Reason classification",POLICY_RETRIEVAL:"Policy retrieval",EVIDENCE_RETRIEVAL:"Evidence retrieval",APPEAL_GENERATION:"Appeal drafting",APPEAL_CRITIC:"Appeal critique",HUMAN_REVIEW:"Human review",SUBMISSION:"Submission",TRACKING:"Tracking",PAYER_RESPONSE:"Payer decision",PAYMENT:"Payment verification"};
const NODE_LABELS={intake:"Intake",extraction:"Extraction",classifier:"Classification",policy_retrieval:"Policy",evidence_retrieval:"Evidence",appeal_generator:"Appeal",appeal_critic:"Critic",human_review:"Human Gate",submission:"Submission",tracking:"Tracking"};
const nice=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const fmt=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
function Pipeline({nodes}){return <div className="pipelineRow">{(nodes||[]).map((n,i)=><React.Fragment key={n.node}><span className={`pipelineNode ${String(n.status).toLowerCase()}`}>{NODE_LABELS[n.node]||n.node}</span>{i<(nodes.length-1)&&<span className="pipelineArrow">→</span>}</React.Fragment>)}</div>}
export default function CaseDetail({id,onBack,onRefresh,review}){const [d,setD]=useState(null),[events,setEvents]=useState([]),[wf,setWf]=useState(null),[out,setOut]=useState(null),[busy,setBusy]=useState(false);const toast=useToast();
 async function refresh(){const [a,b,c,e]=await Promise.all([api.denial(id),api.denialEvents(id),api.denialWorkflow(id).catch(()=>null),api.outcome(id).catch(()=>null)]);setD(a);setEvents(b);setWf(c);setOut(e)} useEffect(()=>{refresh()},[id]);
 if(!d)return <div className="emptyState">Loading case…</div>;
 async function run(){setBusy(true);try{await api.analyzeDenial(id);await refresh();onRefresh();toast('AI workflow completed to its current gate.','good')}catch(e){toast(e.message||'Analysis failed.','warn')}finally{setBusy(false)}}
 async function decide(decision){setBusy(true);try{await review(id,decision);await refresh();onRefresh();toast(decision==='APPROVE'?'Appeal approved and submitted.':decision==='REJECT'?'Case rejected.':'More evidence requested.','good')}catch(e){toast(e.message||'Review failed.','warn')}finally{setBusy(false)}}
 async function simulatePayer(){setBusy(true);try{await api.simulate(id);await refresh();onRefresh();toast('Payer simulator approved the appeal. Payment is now pending.','good')}catch(e){toast(e.message,'warn')}finally{setBusy(false)}}
 async function simulatePayment(){setBusy(true);try{const amount=out?.approved_amount||d.amount;await api.payment(id,amount,'PAID');await refresh();onRefresh();toast('Payment verified. Case completion rules passed.','good')}catch(e){toast(e.message,'warn')}finally{setBusy(false)}}
 async function download(){const {jsPDF}=await import('jspdf');const doc=new jsPDF({unit:'pt',format:'letter'});let y=55;doc.setFontSize(17);doc.text('Denial Recovery Desk — Appeal',55,y);y+=25;doc.setFontSize(10);doc.text(`Claim ${d.claim_no} · ${d.payer} · ${fmt(d.amount)}`,55,y);y+=30;doc.setFontSize(11);doc.text('Appeal',55,y);y+=18;doc.setFontSize(9);for(const line of doc.splitTextToSize(d.appeal||'No appeal draft available.',500)){if(y>740){doc.addPage();y=55}doc.text(line,55,y);y+=13}doc.save(`appeal-${d.claim_no}.pdf`)}
 const caseStatus=out?.case_status||d.status; return <section className="caseView"><button className="back" onClick={onBack}>← Back to queue</button><div className="caseTop"><div><div className="eyebrow">CASE DR-{String(d.id).padStart(4,'0')}</div><h1>{d.claim_no}</h1><p>{d.payer} · {nice(d.reason)||'Unclassified denial'}</p></div><span className={`status ${caseStatus.toLowerCase()}`}>{nice(caseStatus)}</span></div><div className="caseGrid"><section className="panel"><div className="panelTitle"><h2>AI Case Analysis</h2><span className="confTag high">{Math.round((d.confidence||0)*100)}% confidence</span></div><div className="score"><strong>{Math.round((d.confidence||0)*100)}%</strong><span>AI confidence</span></div>{wf?.nodes&&<><h3>LangGraph workflow</h3><Pipeline nodes={wf.nodes}/></>}{d.status==='NEW'&&<button className="casePrimary" disabled={busy} onClick={run}><Icon name="bot"/> {busy?'Running…':'Analyze Denial'}</button>}<h3>Claim</h3><div className="infoGrid"><div><span>Claim amount</span><b>{fmt(d.amount)}</b></div><div><span>Payer</span><b>{d.payer}</b></div><div><span>Submission</span><b>{d.submission_id||'Not submitted'}</b></div><div><span>Recovery probability</span><b>{Math.round((d.recovery_probability||0)*100)}%</b></div></div><h3>Denial reason</h3><div className="reason">{nice(d.reason)||'Not yet classified'}</div><h3>AI explanation</h3><p className="copy">{d.explanation||'No explanation returned.'}</p><h3>Evidence & policy citations</h3><pre>{[...(d.policy_citations||[]),...(d.evidence_citations||[])].map((x,i)=>`[${x.source||'source'}] ${x.content||x.text||JSON.stringify(x)}`).join('\n\n')||d.evidence||'No evidence retrieved.'}</pre></section>
 <section className="panel"><div className="panelTitle"><h2>Appeal & Recovery</h2><span>AI + HUMAN CONTROL</span></div><pre className="appeal">{d.appeal||'Appeal draft will appear after processing.'}</pre><div className="criticBox"><div><span>AI Critic Score</span><strong>{Math.round(d.appeal_score||0)}/100</strong></div><div><span>Recommendation</span><b>{nice(d.appeal_recommendation)||'—'}</b></div></div>{(d.appeal_issues||[]).length>0&&<p className="issueLine">⚠ {d.appeal_issues.join(' · ')}</p>}<div className="actions"><button onClick={download}><Icon name="report"/> Download PDF</button>{d.status==='HUMAN_REVIEW'&&<><button className="casePrimary" disabled={busy} onClick={()=>decide('APPROVE')}><Icon name="check"/> Approve & Submit</button><button className="secondary" disabled={busy} onClick={()=>decide('REQUEST_MORE_EVIDENCE')}>Request Evidence</button><button className="danger" disabled={busy} onClick={()=>decide('REJECT')}>Reject</button></>}</div><h3>Outcome tracking</h3><div className="outcomeSteps"><Step label="Appeal submitted" ok={!!d.submission_id}/><Step label="Payer decision" ok={out?.payer_status==='APPROVED'} active={out?.payer_status==='PENDING'}/><Step label="Payment verified" ok={out?.payment_verified} active={out?.payer_status==='APPROVED'&&!out?.payment_verified}/><Step label="Case completed" ok={out?.case_status==='COMPLETED'}/></div><div className="paymentCard"><div><span>Approved</span><b>{fmt(out?.approved_amount||0)}</b></div><div><span>Paid</span><b>{fmt(out?.paid_amount||0)}</b></div><div><span>Outstanding</span><b>{fmt(out?.outstanding_amount||0)}</b></div></div><div className="actions outcomeActions">{d.submission_id&&(!out||out.payer_status==='SUBMITTED'||out.payer_status==='NOT_SUBMITTED'||out.payer_status==='PENDING')&&<button className="secondary" disabled={busy} onClick={simulatePayer}><Icon name="track"/> Simulate Payer Approval</button>}{out?.payer_status==='APPROVED'&&!out?.payment_verified&&<button className="casePrimary" disabled={busy} onClick={simulatePayment}><Icon name="money"/> Verify Payment</button>}</div><h3>Audit timeline</h3><ol className="timeline">{events.map(e=><li key={e.id}><span className="tDot"/><div><b>{STAGE_LABELS[e.stage]||e.stage}</b><p>{e.message}</p></div></li>)}{!events.length&&<li className="tEmpty">No events recorded.</li>}</ol></section></div></section>}
function Step({label,ok,active}){return <div className={`outcomeStep ${ok?'ok':active?'active':''}`}><span>{ok?'✓':active?'…':'○'}</span><b>{label}</b></div>}
