import React,{useMemo,useState} from "react";
import Icon from "../icons";
const STATUSES=["","NEW","PROCESSING","AUTO_READY","HUMAN_REVIEW","SUBMITTED","REJECTED","FAILED"];
const REASONS=["","coding_error","missing_prior_authorization","medical_necessity","timely_filing","missing_documentation","eligibility","other"];
const nice=s=>String(s||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const fmt=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
export default function Queue({rows,loading,filters,setFilters,open,onSearch}){const [q,setQ]=useState(filters.q||"");const total=useMemo(()=>rows.reduce((a,r)=>a+Number(r.amount||0),0),[rows]);function submit(e){e.preventDefault();onSearch(q)}function csv(){const h=['case','claim','payer','amount','reason','confidence','status'];const lines=[h.join(',')];rows.forEach(d=>lines.push([`DR-${String(d.id).padStart(4,'0')}`,d.claim_no,d.payer,d.amount,d.reason,d.confidence,d.status].map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));a.download='denial-queue.csv';a.click()}
 return <section className="workspace"><div className="workspaceHead"><div><div className="eyebrow">CASE MANAGEMENT</div><h1>Denial Queue</h1><p>{rows.length} visible cases · {fmt(total)} at stake</p></div><button onClick={csv}><Icon name="report"/> Export CSV</button></div><div className="panel queuePanel"><div className="filtersNew"><form onSubmit={submit}><Icon name="search" size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search claim #, payer, denial reason…"/><button>Search</button></form><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}>{STATUSES.map(x=><option key={x}>{x?nice(x):'All statuses'}</option>)}</select><select value={filters.reason} onChange={e=>setFilters({...filters,reason:e.target.value})}>{REASONS.map(x=><option key={x} value={x}>{x?nice(x):'All reasons'}</option>)}</select></div>{loading?<div className="emptyState">Loading cases…</div>:<div className="tablePanel"><table><thead><tr><th>Claim</th><th>Payer</th><th>Denial reason</th><th>Amount</th><th>AI confidence</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(d=><tr key={d.id}><td><button className="tableLink" onClick={()=>open(d.id)}>{d.claim_no}<small>DR-{String(d.id).padStart(4,'0')}</small></button></td><td>{d.payer}</td><td>{nice(d.reason)||'Unclassified'}</td><td>{fmt(d.amount)}</td><td><div className="confBar"><i style={{width:`${Math.min(100,Math.round((d.confidence||0)*100))}%`}}/></div>{Math.round((d.confidence||0)*100)}%</td><td><span className={`status ${String(d.status).toLowerCase()}`}>{nice(d.status)}</span></td><td><button className="iconBtn" onClick={()=>open(d.id)}><Icon name="arrow" size={14}/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="emptyState">No denials match your filters.</div>}</div>}</div></section>
}
