from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

from app.ai.llm import get_chat_model
from app.ai.prompts.critic import CRITIC_PROMPT


class CriticRecommendation(str, Enum):
    APPROVE_REVIEW = "APPROVE_REVIEW"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class CriticEvaluation(BaseModel):
    score: int = Field(ge=0, le=100)
    confidence: float = Field(ge=0, le=1)
    issues: list[str] = Field(default_factory=list)
    missing_evidence: list[str] = Field(default_factory=list)
    recommendation: CriticRecommendation


def _heuristic_critique(appeal_letter: str, policy_hits: list[dict], evidence_hits: list[dict]) -> CriticEvaluation:
    issues: list[str] = []
    if not policy_hits:
        issues.append("No payer policy citation was retrieved for this appeal.")
    if not evidence_hits:
        issues.append("No supporting evidence was retrieved for this appeal.")
    if "fallback draft" in (appeal_letter or "").lower():
        issues.append("Appeal was generated by the offline fallback drafter, not a live LLM.")
    score = 85 if not issues else max(30, 85 - 25 * len(issues))
    return CriticEvaluation(
        score=score,
        confidence=0.5,
        issues=issues,
        missing_evidence=[] if evidence_hits else ["Supporting evidence documents"],
        recommendation=CriticRecommendation.APPROVE_REVIEW if score >= 80 else CriticRecommendation.HUMAN_REVIEW,
    )


def critique_appeal(
    denial_reason: str, appeal_letter: str, policy_hits: list[dict], evidence_hits: list[dict]
) -> CriticEvaluation:
    from app.ai.chains.appeal_chain import _format_context

    try:
        llm = get_chat_model()
        structured = llm.with_structured_output(CriticEvaluation)
        chain = CRITIC_PROMPT | structured
        result = chain.invoke(
            {
                "denial_reason": denial_reason,
                "policy_context": _format_context(policy_hits),
                "evidence_context": _format_context(evidence_hits),
                "appeal_draft": appeal_letter,
            }
        )
        return result if isinstance(result, CriticEvaluation) else CriticEvaluation.model_validate(result)
    except Exception:
        return _heuristic_critique(appeal_letter, policy_hits, evidence_hits)
